version: '3.9'
services:
  db:
    image: postgres:16.4-alpine3.20
    environment:
      POSTGRES_USER: jos3lo
      POSTGRES_PASSWORD: 3322
      POSTGRES_DB: transportes
    ports:
      - "8000:5432"
    volumes:
      - db_data_transporte:/var/lib/postgresql/data

volumes:
  db_data_transporte:
